swagger: '2.0'
info:
  version: '0.2.2'
  title: "Rememo API"
  license:
    name: MIT
    url: https://github.com/nicolatoscan/rememo-api/blob/main/LICENSE
host: rememo-api.herokuapp.com
basePath: /api/v1
tags:
- name: "auth"
  description: "Authentication"
- name: "users"
  description: "Users"
- name: "collections"
  description: "Collections"
- name: "study"
  description: "Study"
- name: "share"
  description: "Share"
schemes:
- https
consumes:
- application/json
produces:
- application/json

paths:
  /auth/signup:
    post:
      tags:
      - "auth"
      summary: Create a New User
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/SignupUser'
      responses:
        201:
          description: 'Created user'
          schema:
            $ref: '#/definitions/SignupUserResponse'
          examples:
            application/json:
                username: Test Displayname
                email: email@example.com
                displayName: TestUsername
  
  /auth/login:
    post:
      tags:
      - "auth"
      summary: Login
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginUser'
      responses:
        200:
          description: 'Logged in user'
          schema:
            $ref: '#/definitions/SignupUserResponse'
          examples:
            application/json:
                username: Test Displayname
                email: email@example.com
                displayName: TestUsername
                
  /users:
    get:
      tags:
      - "users"
      summary: Get the logged User
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/SignupUserResponse'
          examples:
            application/json:
                username: Test Displayname
                email: email@example.com
                displayName: TestUsername
    delete:
      tags:
      - "users"
      summary: delete the logged User
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginUser'
      responses:
        200:
          description: 'user deleted'
    put:
      tags:
      - "users"
      summary: update the logged User
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/UpdateUser'
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/SignupUserResponse'
          examples:
            application/json:
                username: Test Displayname
                email: email@example.com
                displayName: TestUsername
  
  /collections:
    get:
      tags:
      - "collections"
      summary: Get all the Collections
      responses:
        200:
          description: All the Collections
          schema:
            $ref: '#/definitions/CollectionArray'
          examples:
            application/json:
              [
                {
                  _id: 5fb6e4b522935b001216de8c,
                  index: 1,
                  name: Testing Collection,
                  description: Testing description,
                  owner: TestUsername,
                  languageFrom: null,
                  languageTo: null,
                  words: [
                    {
                      _id: 5fb6e4b522935b001216de8d,
                      index: 1,
                      original: Red,
                      translation: Rosso
                    }
                  ]
                },
                {
                  _id: 6ts6e4b123935b004476de8c,
                  index: 2,
                  name: Testing Collection,
                  description: Testing description,
                  owner: TestUsername,
                  languageFrom: null,
                  languageTo: null,
                  words: [
                    {
                      _id: 6ts6e4b123935b004476de8f,
                      index: 2,
                      original: Green,
                      translation: Verde
                    }
                  ]
                }
              ]
    post:
      tags:
      - "collections"
      summary: Create a new Collection
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Collection'
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/ReturnId'
          examples:
            application/json:
                _id: 0123456789abcdef01234567
  
  /collections/{collectionId}:
    get:
      tags:
      - "collections"
      summary: Get a Collection by its id
      parameters:
        - name: collectionId
          in: path
          required: true
          type: string
      responses:
        200:
          description: A Collection of Words identifiend by its id
          schema:
            $ref: '#/definitions/Collection'
          examples:
            application/json:
                index: 123
                name: My Favorite Colors
                description: All my favorite colors put together!
                owner: Mario
                words: [
                  {
                    index: 456,
                    original: Red,
                    translation: Rosso,
                    languageFrom: English,
                    languageTo: Italiano
                  }
                ]
    put:
      tags:
      - "collections"
      summary: Update a Collection by its id
      parameters:
        - name: collectionId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/UpdateCollection'
      responses:
        204:
          description: 'Collection updated'
    delete:
      tags:
      - "collections"
      summary: Delete a Collection by its id
      parameters:
        - name: collectionId
          in: path
          required: true
          type: string
      responses:
        204:
          description: 'Collection deleted'
  
  /collections/{collectionId}/words:
    post:
      tags:
      - "collections"
      summary: Create a new Collection
      parameters:
        - name: collectionId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Word'
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/Word'
          examples:
            application/json:
                _id: 0123456789abcdef01234567
  
  /collections/{collectionId}/words/{wordId}:
    delete:
      tags:
      - "collections"
      summary: Delete a Word by its id
      parameters:
        - name: collectionId
          in: path
          required: true
          type: string
        - name: wordId
          in: path
          required: true
          type: string
      responses:
        204:
          description: Word deleted
          
  /study/learn/{collectionId}/status:
    get:
      tags:
      - "study"
      summary: Get the Learn State of a Collection
      parameters:
        - name: collectionId
          in: path
          required: true
          type: string
      responses:
        200:
          description: 'An array of objects which defines the Learn State of a Collection'
          schema: 
            $ref: '#/definitions/CollectionLearnState'
          examples:
            application/json: [
                  {
                    wordId: 353hk23j5b23k5bjk2sdfasd,
                    learned: 0.343
                  },
                  {
                    wordId: 891fedf7gd7fgd89f789df7g,
                    learned: 0.575
                  }
                ]
  
  /study/learn/{collectionId}/learned:
    put:
      tags:
      - "study"
      summary: Update the Learn State of a Word
      parameters:
        - name: collectionId
          in: path
          type: string
          required: true
        - name: wordId
          in: query
          type: string
          required: true
        - name: status
          in: query
          type: number
          required: true
      responses:
        204:
          description: 'Word Learn State updated'
          
  /study/learn/{collectionId}/reset:
    put:
      tags:
      - "study"
      summary: Reset the Learn State of a Collection
      parameters:
        - name: collectionId
          in: path
          type: string
          required: true
      responses:
        204:
          description: 'Collection Learn State reseted'
          
  /share/{collectionId}:
    get:
      tags:
      - "share"
      summary: Share a Collection
      parameters:
        - name: collectionId
          in: path
          required: true
          type: string
      responses:
        200:
          description: 'Collection can be shared'
          examples:
            application/json:
                url: share/import/5fbeca7fa4b2a77d62753073

  /share/import/{collectionId}:
    get:
      tags:
      - "share"
      summary: Import a Collection
      parameters:
        - name: collectionId
          in: path
          required: true
          type: string
      responses:
        204:
          description: 'Collection imported'
          
  /stats/test/{collectionId}/word/{wordId}:
    get:
      tags:
      - "stats"
      summary: Get the stats about a word in test
      parameters:
        - name: collectionId
          in: path
          required: true
          type: string
        - name: wordId
          in: path
          required: true
          type: string
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/StatsTest'
          examples:
            application/json:
              correctTest: 0
              wrongTest: 0
          
  /stats/train/{collectionId}/word/{wordId}:
    get:
      tags:
      - "stats"
      summary: Get the stats about a word in train
      parameters:
        - name: collectionId
          in: path
          required: true
          type: string
        - name: wordId
          in: path
          required: true
          type: string
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/StatsTrain'
          examples:
            application/json:
              correctTrain: 0
              wrongTrain: 0

definitions:
  
  StatsTrain:
    title: StatsTest
    type: object
    properties:
      correctTrain:
        type: number
      wrongTrain:
        type: number
  
  StatsTest:
    title: StatsTest
    type: object
    properties:
      correctTest:
        type: number
      wrongTest:
        type: number

  ReturnId:
    title: ReturnId
    type: object
    properties:
      _id:
        type: string
    required:
      - _id
  
  LoginUser:
    title: LoginUser
    type: object
    properties:
      username:
        type: string
      password:
        type: string
    required:
      - username
      - password
  
  SignupUser:
    title: SignupUser
    type: object
    properties:
      username:
        type: string
      password:
        type: string
      displayName:
        type: string
      email:
        type: string
    required:
      - username
      - password
      - displayName
      - email
      
  UpdateUser:
    title: UpdateUser
    type: object
    properties:
      username:
        type: string
      password:
        type: string
      displayName:
        type: string
      email:
        type: string
      newPassword:
        type: string
    required:
      - username
      - password

  SignupUserResponse:
    title: SignupUser
    type: object
    properties:
      username:
        type: string
      displayName:
        type: string
      email:
        type: string
    required:
      - username
      - displayName
      - email
  
  Collection:
    title: Collection
    type: object
    properties:
      index:
        type: integer
      name:
        type: string
      description:
        type: string
      owner:
        type: string
      languageFrom:
        type: string
      languageTo:
        type: string
      words:
        type: array
        items:
          $ref: '#/definitions/Word'
    required:
      - index
      - name
      - description
      - owner
      - words
  
  CollectionArray:
    title: CollectionArray
    type: array
    items:
      $ref: '#/definitions/Collection'
  
  UpdateCollection:
    title: Collection
    type: object
    properties:
      index:
        type: integer
      name:
        type: string
      description:
        type: string
      languageFrom:
        type: string
      languageTo:
        type: string
    required:
      - index
      - name
      - description
  
  Word:
    title: Word
    type: object
    properties:
      index:
        type: integer
      original:
        type: string
      translation:
        type: string
      languageFrom:
        type: string
      languageTo:
        type: string
    required:
      - index
      - original
      - translation
      
  CollectionLearnState:
    title: CollectionLearnState
    type: array
    items:
      $ref: '#/definitions/WordLearnState'
      
  WordLearnState:
    title: WordLearnState
    type: object
    properties:
      wordId:
        type: string
      learned:
        type: number
    required:
      - wordId
      - learned
