name: Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install node dependencies
        run: npm install
      
      - name: Run tests
        run: npm test
        env:
          PORT: 4000
          DEFAULT_DB: rememo-github
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          CRYPTO_SECRET: ${{ secrets.CRYPTO_SECRET }}
